import assert from "node:assert/strict";
import test from "node:test";
import { createSSRApp } from "vue";
import { renderToString } from "@vue/server-renderer";
import type { SkinPluginDocument } from "../../../src/shared/skin-plugin.js";
import {
  parseSkinExtensionUiOutput,
  SKIN_EXTENSION_UI_OUTPUT_LIMIT_BYTES,
  SkinExtensionUiOutputError,
} from "../../../src/shared/skin-extension-ui.js";
import SkinPluginOutlet from "../components/SkinPluginOutlet.js";

function outputDocument(componentId = "runtime-ui", root?: Record<string, unknown>, permissions: string[] = [], actions: Record<string, unknown> = {}, state?: Record<string, unknown>): string {
  return JSON.stringify({
    schemaVersion: 3,
    components: [{
      id: componentId,
      name: "Runtime UI",
      page: "voice",
      accessibleName: "Runtime UI",
      permissions,
      actions,
      ...(state ? { state } : {}),
      root: root ?? { tag: "section", children: [{ text: "Generated by Wasm" }] },
    }],
  });
}

function expectOutputError(source: string, code: string): void {
  assert.throws(() => parseSkinExtensionUiOutput(source), (error: unknown) =>
    error instanceof SkinExtensionUiOutputError && error.code === code);
}

test("Wasm UI output uses the v3 schema and supports local-only interaction", () => {
  const document = parseSkinExtensionUiOutput(outputDocument("runtime-ui", {
    tag: "section",
    children: [
      { tag: "button", attributes: { type: "button" }, events: { click: "toggle" }, children: [{ text: "Toggle" }] },
      { tag: "p", when: { path: "state.open", equals: true }, children: [{ text: "Expanded" }] },
    ],
  }, [], { toggle: { type: "ui.toggleState", args: { key: "open" } } }, { open: false }));

  assert.equal(document.schemaVersion, 3);
  assert.equal(document.components[0].actions.toggle.type, "ui.toggleState");
});

test("Wasm UI output rejects malformed, oversized, legacy, and capability-bearing documents", () => {
  expectOutputError("{", "SKIN_EXTENSION_UI_OUTPUT_JSON");
  expectOutputError(" ".repeat(SKIN_EXTENSION_UI_OUTPUT_LIMIT_BYTES + 1), "SKIN_EXTENSION_UI_OUTPUT_SIZE");
  expectOutputError(JSON.stringify({ schemaVersion: 2, components: [{
    id: "runtime-ui", name: "Runtime UI", page: "voice", accessibleName: "Runtime UI", permissions: [], actions: {}, root: { tag: "section" },
  }] }), "SKIN_EXTENSION_UI_SCHEMA_UNSUPPORTED");
  expectOutputError(outputDocument("runtime-ui", undefined, ["session.status.read"]), "SKIN_EXTENSION_UI_CAPABILITY_UNSUPPORTED");
  expectOutputError(outputDocument("runtime-ui", undefined, [], { disconnect: { type: "voice.disconnect", args: {} } }), "SKIN_EXTENSION_UI_OUTPUT_SCHEMA");
  expectOutputError(outputDocument("runtime-ui", { widget: "voice.audio-controls" }), "SKIN_EXTENSION_UI_WIDGET_UNSUPPORTED");
  expectOutputError(outputDocument("runtime-ui", { tag: "p", text: "{{session.status.channelName}}" }), "SKIN_EXTENSION_UI_OUTPUT_SCHEMA");
});

test("SkinPluginOutlet renders validated dynamic output and preserves package UI on collisions", async () => {
  const document: SkinPluginDocument = {
    schemaVersion: 3,
    components: [{
      id: "base-ui",
      name: "Base UI",
      page: "voice",
      accessibleName: "Base UI",
      permissions: [],
      actions: {},
      root: { tag: "p", children: [{ text: "Package UI" }] },
    }],
  };
  const props = {
    skinId: "community.test",
    skinVersion: "1.0.0",
    document,
    page: "voice" as const,
    data: {},
    assets: {},
    actions: {},
  };

  const html = await renderToString(createSSRApp(SkinPluginOutlet, {
    ...props,
    extensionOutput: outputDocument("runtime-ui"),
  }));
  assert.match(html, /data-ws-plugin-component="base-ui"/);
  assert.match(html, /data-ws-plugin-component="runtime-ui"/);
  assert.match(html, /Generated by Wasm/);

  const collisionHtml = await renderToString(createSSRApp(SkinPluginOutlet, {
    ...props,
    extensionOutput: outputDocument("base-ui"),
  }));
  assert.match(collisionHtml, /data-ws-plugin-component="base-ui"/);
  assert.doesNotMatch(collisionHtml, /Generated by Wasm/);
  assert.match(collisionHtml, /Package UI/);
});

test("skin-authored DOM nodes expose independent layout parts and retain touch bounds for controls", async () => {
  const document: SkinPluginDocument = {
    schemaVersion: 3,
    components: [{
      id: "voice-toolbar",
      name: "Voice toolbar",
      page: "voice",
      accessibleName: "Voice toolbar",
      permissions: [],
      actions: {},
      root: {
        tag: "section",
        children: [
          { tag: "button", part: "disconnect", attributes: { type: "button" }, children: [{ text: "Disconnect" }] },
          { text: "Voice tools", part: "caption" },
        ],
      },
    }],
  };
  const html = await renderToString(createSSRApp(SkinPluginOutlet, {
    skinId: "community.test",
    skinVersion: "1.0.0",
    document,
    page: "voice",
    data: {},
    assets: {},
    actions: {},
  }));
  assert.match(html, /data-ws-part="skin\.voice\.voice-toolbar"/);
  assert.match(html, /data-ws-part="skin\.voice\.voice-toolbar\.node-root"/);
  assert.match(html, /data-ws-part="skin\.voice\.voice-toolbar\.control-part-disconnect"/);
  assert.match(html, /data-ws-part="skin\.voice\.voice-toolbar\.part-caption"/);
});
